version: 0.2

run_as: dockremap

phases:
  #install:
    #runtime-versions:
      #java: corretto11
      #nodejs: 12
     # python: 3.7
    #commands:
      #- npm install -g bower @bazel/bazelisk
     # - yum install -y maven zip unzip curl gcc-c++
   ##   - git submodule init
  #- git submodule update --recursive
  build:
    commands:
      - echo "-----------TEST---------------"
      #- bazel test --test_env=GERRIT_USE_SSH=NO --test_tag_filters=-ssh,-delete-project,-git-protocol-v2,-git-upload-archive //...
      #- bazel build :release
       - whoami
#artifacts:
 # files:
 #   - bazel-bin/release.war 
  
