version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 12
      python: 3.7
    commands:
      - yum install -y maven zip unzip curl gcc-c++
      - git submodule init
      - git submodule update --recursive
  pre_build:
    commands:
      - npm install -g bower @bazel/bazelisk
  build:
    commands:
      - echo "-----------TEST---------------"
      #- bazel test --remote_cache=http://$IP_CACHE:9090 --test_env=GERRIT_USE_SSH=NO --test_tag_filters=-ssh,-delete-project,-git-protocol-v2,-git-upload-archive //...
      - bazel build --remote_cache=http://$IP_CACHE:9090 :release
      - cp bazel-bin/release.war ./ebs
  
